### ISSUE TITLE
[Bug] mysql 数据源有何要求，请给出示例吧 

### ISSUE THREAD

**Issue by geekyouth** [isxcode/flink-yun#134]
### Branch name (分支名)

main

### Bug description (缺陷描述)

使用 mysql8 替换 h2 为什么启动报错了，flyway 脚本不兼容 mysql 8 吗？从报错日志来看，Flyway 依然识别为 h2 数据库

![image](https://github.com/user-attachments/assets/d1543a0a-6c77-46a8-a54a-bca9f14f1ad1)

![image](https://github.com/user-attachments/assets/327d68be-9649-413b-93aa-cd3e4b2e9b4a)

```
networks:
  fullstack:
    name: fullstack
    ipam:
      config:
        - subnet: 172.16.1.0/24

services:
  # 至流云 https://zhiliuyun.isxcode.com/docs/zh/1/0-docker
  flinkyun:
    image: isxcode/zhiliuyun
    hostname: flinkyun
    container_name: flinkyun-dev
    ports:
      - "8280:8080"
    environment:
      TZ: Asia/Shanghai
      ACTIVE_ENV: demo
      ADMIN_PASSWORD: 123456
    volumes:
      - ./config:/etc/flink-yun/conf
      - ./_docker-data/resources:/var/lib/flink-yun
    networks:
      fullstack:

```

```
spring:
  jpa:
    database: mysql # 可配置h2或者mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/flink_yun_dev
    username: flink_yun_dev
    password: flink_yun_dev
  flyway:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/flink_yun_dev
    username: flink_yun_dev
    password: flink_yun_dev
    locations: classpath:db/migration/mysql  #  可配置classpath:db/migration/h2或者classpath:db/migration/mysql
  quartz:
    properties:
      org.quartz.dataSource.quartzDataSource.driver: com.mysql.jdbc.Driver
      org.quartz.dataSource.quartzDataSource.URL: jdbc:mysql://mysql:3306/flink_yun_dev
      org.quartz.dataSource.quartzDataSource.user: flink_yun_dev
      org.quartz.dataSource.quartzDataSource.password: flink_yun_dev

```

```
Caused by: java.sql.SQLException: sql injection violation, dbType h2, , druid-version 1.2.16, syntax error: TODO. pos 470, line 12, column 17, token LITERAL_ALIAS "flyway_schema_history_pk" : CREATE TABLE IF NOT EXISTS "PUBLIC"."flyway_schema_history" (
2024-10-11T02:46:56.286354942Z     "installed_rank" INT NOT NULL,
2024-10-11T02:46:56.286357842Z     "version" VARCHAR(50),
2024-10-11T02:46:56.286361142Z     "description" VARCHAR(200) NOT NULL,
2024-10-11T02:46:56.286364543Z     "type" VARCHAR(20) NOT NULL,
2024-10-11T02:46:56.286367743Z     "script" VARCHAR(1000) NOT NULL,
2024-10-11T02:46:56.286371143Z     "checksum" INT,
2024-10-11T02:46:56.286374543Z     "installed_by" VARCHAR(100) NOT NULL,
2024-10-11T02:46:56.286377843Z     "installed_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
2024-10-11T02:46:56.286381243Z     "execution_time" INT NOT NULL,
2024-10-11T02:46:56.286388843Z     "success" BOOLEAN NOT NULL,
2024-10-11T02:46:56.286393544Z     CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")
2024-10-11T02:46:56.286401744Z ) AS SELECT -1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'SA', CURRENT_TIMESTAMP, 0, TRUE
2024-10-11T02:46:56.286407444Z 	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:828) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286411644Z 	at com.alibaba.druid.wall.WallFilter.check(WallFilter.java:800) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286415644Z 	at com.alibaba.druid.wall.WallFilter.statement_execute(WallFilter.java:432) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286420445Z 	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2991) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286428345Z 	at com.alibaba.druid.filter.FilterAdapter.statement_execute(FilterAdapter.java:2483) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286433345Z 	at com.alibaba.druid.filter.FilterEventAdapter.statement_execute(FilterEventAdapter.java:182) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286437445Z 	at com.alibaba.druid.filter.FilterChainImpl.statement_execute(FilterChainImpl.java:2991) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286441245Z 	at com.alibaba.druid.proxy.jdbc.StatementProxyImpl.execute(StatementProxyImpl.java:141) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286445345Z 	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:635) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286449746Z 	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201) ~[flyway-core-9.16.3.jar!/:na]
2024-10-11T02:46:56.286453746Z 	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95) ~[flyway-core-9.16.3.jar!/:na]
2024-10-11T02:46:56.286457546Z 	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210) ~[flyway-core-9.16.3.jar!/:na]
2024-10-11T02:46:56.286463646Z 	... 41 common frames omitted
2024-10-11T02:46:56.286467746Z Caused by: com.alibaba.druid.sql.parser.ParserException: TODO. pos 470, line 12, column 17, token LITERAL_ALIAS "flyway_schema_history_pk"
2024-10-11T02:46:56.286472546Z 	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseConstraint(MySqlCreateTableParser.java:1783) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286477046Z 	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCreateTable(MySqlCreateTableParser.java:363) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286481647Z 	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreate(MySqlStatementParser.java:296) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286486647Z 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:245) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286490847Z 	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:112) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286500147Z 	at com.alibaba.druid.wall.WallProvider.checkInternal(WallProvider.java:618) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286504847Z 	at com.alibaba.druid.wall.WallProvider.check(WallProvider.java:572) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286509248Z 	at com.alibaba.druid.wall.WallFilter.checkInternal(WallFilter.java:805) ~[druid-1.2.16.jar!/:na]
2024-10-11T02:46:56.286513448Z 	... 52 common frames omitted
```

**Comment by ispong** [comment]
你这配置文件版本看着不对呀

**Comment by ispong** [comment]
不需要单独配置flyway的数据库，只需要配置spring的datasource即可
![image](https://github.com/user-attachments/assets/645f5627-e4d7-40de-a2c9-42ca8b5647ae)

**Comment by ispong** [comment]
重新拉一下代码吧

**Comment by ispong** [comment]
jpa 啥的都不需要额外的配置

**Comment by ispong** [comment]
![image](https://github.com/user-attachments/assets/64d699b1-6130-47a1-896c-abd5f484f785)

**Comment by geekyouth** [comment]
main 分支也没更新过代码，修改配置文件如下，重新 down 之后 up ，启动后日志显示还是使用 H2 数据库：

![image](https://github.com/user-attachments/assets/4f83a319-87a3-419e-bafc-f689b701ab1b)

这里是说明文档 https://zhiliuyun.isxcode.com/docs/zh/1/0-docker

**Comment by geekyouth** [comment]
已解决：

```
    volumes:
      - ./config/:/etc/zhiliuyun/conf/
```
